### ISSUE TITLE
ホワイトボックステスト

### ISSUE THREAD

**Issue by laco0416** [Atoze/HTTP_Server#13]
書いていく

**Comment by laco0416** [comment]
- 使用している画像はすべて著作権フリーなものですか？

**Comment by laco0416** [comment]
- JavaScriptファイルのContent-Typeが `application/js` になってる

あまり見ないMIME typeだと思う。普通は `text/javascript` かな？

**Comment by laco0416** [comment]
- JPEGファイルのContent-Typeが `image/jpg` になってる

一般的には `image/jpeg` のはず

**Comment by laco0416** [comment]
複数リクエスト同時にさばけるようになっててすばらしい

**Comment by laco0416** [comment]
- 巨大なファイルを配信しようとするとサーバーが落ちる

1.9GBのHTMLファイルを配信させたら途中で落ちた

```
Exception in thread "Thread-93" java.lang.RuntimeException: java.net.SocketException: Broken pipe
        at jp.co.topgate.atoze.web.HTTPResponse.writeTo(HTTPResponse.java:75)
        at jp.co.topgate.atoze.web.HTTPHandler.handlerGET(HTTPHandler.java:31)
        at jp.co.topgate.atoze.web.Server.run(Server.java:45)
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
        at jp.co.topgate.atoze.web.HTTPResponse.writeTo(HTTPResponse.java:72)
```

**Comment by laco0416** [comment]
asada君のは時間はかかったけど巨大なファイルも最終的にはダウンロードできた

**Comment by laco0416** [comment]
1回目終了！割ときっちり作られてた

**Comment by asada0701** [comment]
複数リクエスト対応。。
まじか、参考にさせてもらいます。

**Comment by laco0416** [comment]
巨大ファイル、エラーを吐きながらも進行している… なんかダウンロードできそうな雰囲気になってきた

**Comment by Atoze** [comment]
ありがとうございます！Content-Typeは確認不足でした…GIFファイルが著作権まわり怪しいので確認してきます

**Comment by vvakame** [comment]
`application/javascript` がトレンディだった気がする(要出典

**Comment by laco0416** [comment]
`application/javascript` が推奨っぽいですね https://tools.ietf.org/html/rfc4329#page-9

**Comment by Atoze** [comment]
* [] JavascriptファイルのMIME typeを`application/javascript`に変更
* [ ] JPGファイルのMIME typeを`image/jpeg`に統一
* [ ] 巨大ファイルのやりとり時にBroken pipeエラーを引き起こしてしまう

**Comment by Atoze** [comment]
Broken pipeエラーはひとまず置いておくことにします
